on:
  push:
    branches:
      - 1.x

name: Package

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: 1.x
    - name: Package
      run: |
        npm ci
        npm test
        npm run package
    - name: Commit
      run: |
        git config --global user.name "GitHub Actions"
        git add dist/
        git commit -m "chore: Update dist" || echo "No changes to commit"
        git push origin HEAD:1.x