on:
  push:
    branches:
      - integ-tests

name: Integration Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print current build ID
      run: |
        echo Integration test run: githubactionsamazonecrlogin-Wwf7ijrjMZH6:2270d9ac-34a3-4dc4-a061-6a17fa04129d

    - name: Configure AWS credentials
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@6f6f10f099d5245e429376d788ad4f74db9a465e

    - name: Tag and push an image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: github-actions-amazon-ecr-login-integ-tests
        IMAGE_TAG: latest
      run: |
        docker pull amazonlinux
        docker tag amazonlinux $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Login to Amazon ECR using explicit registry ID
      uses: aws-actions/amazon-ecr-login@6f6f10f099d5245e429376d788ad4f74db9a465e
      with:
        registries: ${{ steps.configure-aws-credentials.outputs.aws-account-id }}
