on:
  push:
    branches:
      - integ-tests

name: Integration Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print current build ID
      run: |
        echo Integration test run: githubactionsamazonecrlogin-Wwf7ijrjMZH6:78c7fd58-1f86-4e41-a254-32df01eb7403

    - name: Configure AWS credentials
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@1d5211ae8c3827b1d9f9f1bef4cc7a9d829d2541

    - name: Tag and push an image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: github-actions-amazon-ecr-login-integ-tests
        IMAGE_TAG: latest
      run: |
        docker pull amazonlinux
        docker tag amazonlinux $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Login to Amazon ECR using explicit registry ID
      uses: aws-actions/amazon-ecr-login@1d5211ae8c3827b1d9f9f1bef4cc7a9d829d2541
      with:
        registries: ${{ steps.configure-aws-credentials.outputs.aws-account-id }}

    - name: Logout of Amazon ECR
      if: always()
      run: docker logout ${{ steps.login-ecr.outputs.registry }}